<?php

/**
 * Implements hook_theme().
 */
function vox_module_theme($existing, $type, $theme, $path) {
  return [
    'vox_banner' => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'banner' => NULL,
        'search' => NULL,
      ],
    ],
    'vox_news_latest' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'vox_event_latest' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
}
